# Generated by Django 5.1.2 on 2024-11-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='lat',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='lng',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
